/*
 Copyright (c) 2020, Stephen Gold
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright
 notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.
 * Neither the name of the copyright holder nor the names of its contributors
 may be used to endorse or promote products derived from this software without
 specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package jme3utilities.minie.test.mesh;

import com.jme3.math.FastMath;
import com.jme3.math.Vector2f;
import com.jme3.math.Vector3f;
import com.jme3.scene.Mesh;
import com.jme3.scene.VertexBuffer;
import com.jme3.scene.mesh.IndexBuffer;
import com.jme3.util.BufferUtils;
import java.nio.Buffer;
import java.nio.FloatBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import jme3utilities.MyMesh;
import jme3utilities.Validate;
import jme3utilities.math.MyBuffer;
import jme3utilities.math.MyVector3f;

/**
 * A 3-D, static, Triangles-mode mesh (with indices, normals, and texture
 * coordinates) that approximates a sphere, generated by subdividing the faces
 * of a regular octahedron. The resulting mesh is more isotropic than a U-V
 * sphere and handles textures better than an icosphere.
 * <p>
 * The texture coordinates are similar to Sphere.TextureMode.Projected, only
 * with the U values mirrored and offset.
 *
 * @author Stephen Gold sgold@sonic.net
 *
 * Based on Icosphere by jayfella.
 */
public class Octasphere extends Mesh {
    // *************************************************************************
    // constants and loggers

    /**
     * number of axes in a vector
     */
    final private static int numAxes = 3;
    /**
     * number of vertices per triangle
     */
    final private static int vpt = 3;
    /**
     * message logger for this class
     */
    final public static Logger logger
            = Logger.getLogger(Octasphere.class.getName());
    // *************************************************************************
    // fields

    /**
     * distance of each vertex from the center (&gt;0)
     */
    final private float radius;
    /**
     * next vertex index to be assigned
     */
    private int nextVertexIndex = 0;
    /**
     * vertex indices of the 8 triangular faces in a regular octahedron
     */
    final private static int[] octaIndices = {
        0, 2, 5, 1, 4, 3,
        0, 3, 4, 1, 5, 2,
        0, 4, 2, 1, 3, 5,
        0, 5, 3, 1, 2, 4
    };
    /**
     * map vertex indices to location vectors in mesh coordinates, all with
     * length=radius
     */
    final private List<Vector3f> locations = new ArrayList<>(128);
    /**
     * cache to avoid duplicate vertices: map index pairs to midpoint indices
     */
    final private Map<Long, Integer> midpointCache = new HashMap<>(480);
    /**
     * vertex locations in a regular octahedron with radius=1
     */
    final private static Vector3f[] octaLocations = {
        new Vector3f(-1f, 0f, 0f), new Vector3f(1f, 0f, 0f),
        new Vector3f(0f, -1f, 0f), new Vector3f(0f, 1f, 0f),
        new Vector3f(0f, 0f, -1f), new Vector3f(0f, 0f, 1f)
    };
    // *************************************************************************
    // constructors

    /**
     * No-argument constructor needed by SavableClassUtil.
     */
    protected Octasphere() {
        radius = 1f;
    }

    /**
     * Instantiate an octasphere with the specified radius and number of
     * refinement steps:
     * <ul><li>
     * 0 steps &rarr; 6 vertices, 12 edges, 8 triangular faces
     * </li><li>
     * 1 step &rarr; 18 vertices, 48 edges, 32 triangular faces
     * </li><li>
     * 2 steps &rarr; 66 vertices, 192 edges, 128 triangular faces
     * </li><li>
     * etcetera
     * </ul>
     *
     * The center is at (0,0,0). All triangles face outward.
     *
     * @param numRefineSteps the desired number of refinement steps (&ge;0)
     * @param radius the desired radius (in mesh units, &gt;0)
     */
    public Octasphere(int numRefineSteps, float radius) {
        Validate.nonNegative(numRefineSteps, "number of refinement steps");
        Validate.positive(radius, "radius");

        this.radius = radius;
        /*
         *  Add the 6 vertices of a regular octahedron of radius=1.
         */
        for (Vector3f octaLocation : octaLocations) {
            addVertex(octaLocation);
        }
        /*
         *  Add the 8 triangular faces of a regular octahedron.
         */
        List<Integer> faces = new ArrayList<>();
        for (int octaIndex : octaIndices) {
            faces.add(octaIndex);
        }

        for (int stepIndex = 0; stepIndex < numRefineSteps; ++stepIndex) {
            List<Integer> newFaces = new ArrayList<>();
            /*
             * A refinement step: cut each edge in half; for each
             * triangle in faces, add 4 triangles to newFaces.
             */
            for (int j = 0; j < faces.size(); j += vpt) {
                int v1 = faces.get(j);
                int v2 = faces.get(j + 1);
                int v3 = faces.get(j + 2);

                int a = midpointIndex(v1, v2);
                int b = midpointIndex(v2, v3);
                int c = midpointIndex(v3, v1);

                newFaces.add(v1);
                newFaces.add(a);
                newFaces.add(c);

                newFaces.add(v2);
                newFaces.add(b);
                newFaces.add(a);

                newFaces.add(v3);
                newFaces.add(c);
                newFaces.add(b);

                newFaces.add(a);
                newFaces.add(b);
                newFaces.add(c);
            }

            faces = newFaces;
        }
        midpointCache.clear();

        int numVertices = locations.size();
        int numFloats = numAxes * numVertices;
        FloatBuffer posBuffer = BufferUtils.createFloatBuffer(numFloats);
        for (Vector3f pos : locations) {
            posBuffer.put(pos.x).put(pos.y).put(pos.z);
        }
        posBuffer.flip();
        setBuffer(VertexBuffer.Type.Position, numAxes, posBuffer);

        int numIndices = faces.size();
        IndexBuffer ib = IndexBuffer.createIndexBuffer(numVertices, numIndices);
        for (int i = 0; i < numIndices; ++i) {
            int vertexIndex = faces.get(i);
            MyBuffer.putRelative(ib, vertexIndex);
        }
        VertexBuffer.Format ibFormat = MyBuffer.getFormat(ib);
        Buffer ibData = ib.getBuffer();
        ibData.flip();
        setBuffer(VertexBuffer.Type.Index, vpt, ibFormat, ibData);

        FloatBuffer uvBuffer = BufferUtils.createFloatBuffer(2 * numVertices);
        for (Vector3f pos : locations) {
            Vector2f longLat = cartesianToSpherical(pos);
            float u = 0.5f + longLat.x / FastMath.TWO_PI;
            // u = MyMath.modulo(0.5f - u, 1f);// to match TextureMode.Projected
            float v = 0.5f + longLat.y / FastMath.PI;
            uvBuffer.put(u).put(v);
        }
        uvBuffer.flip();
        setBuffer(VertexBuffer.Type.TexCoord, 2, uvBuffer);

        MyMesh.addSphereNormals(this);

        locations.clear();
        updateBound();
        setStatic();
    }
    // *************************************************************************
    // private methods

    /**
     * Add a vertex to the lists of locations and normals.
     *
     * @param location the approximate vertex location (in mesh coordinates, not
     * null, unaffected)
     * @return the index assigned to the new vertex (&ge;0)
     */
    private int addVertex(Vector3f location) {
        float length = location.length();
        locations.add(location.mult(radius / length));
        int result = nextVertexIndex;
        ++nextVertexIndex;

        return result;
    }

    /**
     * Transform 3-D Cartesian coordinates to longitude and latitude.
     *
     * @param input the location to transform (z=distance north of the
     * equatorial plane, not null, unaffected)
     * @return a new vector (x=west longitude in radians, y=north latitude in
     * radians)
     */
    private Vector2f cartesianToSpherical(Vector3f input) {
        Vector2f result = new Vector2f();
        float length = input.length();

        if (input.x != 0f || input.y != 0f) {
            result.x = -FastMath.atan2(input.y, input.x);
        } else {
            result.x = 0f;
        }

        if (length > 0f) {
            result.y = FastMath.asin(input.z / length);
        } else {
            result.y = 0f;
        }

        return result;
    }

    /**
     * Determine the index of the vertex halfway between the indexed vertices.
     *
     * @param p1 the index of the first input vertex (&ge;0)
     * @param p2 the index of the 2nd input vertex (&ge;0)
     * @return the midpoint index (&ge;0)
     */
    private int midpointIndex(int p1, int p2) {
        /*
         * Check whether the midpoint has already been assigned an index.
         */
        boolean firstIsSmaller = p1 < p2;
        long smallerIndex = firstIsSmaller ? p1 : p2;
        long greaterIndex = firstIsSmaller ? p2 : p1;
        long key = (smallerIndex << 32) + greaterIndex;
        Integer cachedIndex = midpointCache.get(key);
        if (cachedIndex != null) {
            return cachedIndex;
        }
        /*
         * The midpoint vertex is not in the cache: calculate its location.
         */
        Vector3f loc1 = locations.get(p1);
        Vector3f loc2 = locations.get(p2);
        Vector3f middleLocation = MyVector3f.midpoint(loc1, loc2, null);
        /*
         * addVertex() adjusts the location to the sphere.
         */
        int newIndex = addVertex(middleLocation);
        /*
         * Add the new vertex to the midpoint cache.
         */
        midpointCache.put(key, newIndex);

        return newIndex;
    }
}
