= How to build Minie from source
:Project: Minie

{Project} is free, open-source software.

While pre-built library artifacts
can be downloaded from GitHub and the Maven Central Repository,
some people prefer to build them from source.

You can also build a local copy of the documentation website (including HTML).
This is useful if you are editing the documentation,
or if your Internet access is limited or unreliable.


== Libraries

=== Standard build

The _standard build_ of the Minie library includes a non-debug,
single-precision native library for each of the 10 platforms Minie supports.

Here's the recommended procedure:

. Install a https://adoptium.net/releases.html[Java Development Kit (JDK)],
  version 17 or higher,
  if you don't already have one.
. Point the `JAVA_HOME` environment variable to your JDK installation:
  (The path might be something like "C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot"
  or "/usr/lib/jvm/java-21-openjdk-amd64/" or
  "/Library/Java/JavaVirtualMachines/liberica-jdk-17-full.jdk/Contents/Home" .)
.. using Bash or Zsh: `export JAVA_HOME="` *path to installation* `"`
.. using https://fishshell.com/[Fish]: `set -g JAVA_HOME "` *path to installation* `"`
.. using Windows Command Prompt: `set JAVA_HOME="` *path to installation* `"`
.. using PowerShell: `$env:JAVA_HOME = '` *path to installation* `'`
. Download and extract the {Project} source code from GitHub:
.. using https://git-scm.com[Git]:
... `git clone https://github.com/stephengold/Minie.git`
... `cd Minie`
... `git checkout -b latest 9.0.1`
.. using a web browser:
... browse to https://github.com/stephengold/Minie/releases/latest
... follow the "Source code (zip)" link
... save the ZIP file
... extract the contents of the saved ZIP file
... `cd` to the extracted directory
. Run the https://gradle.org[Gradle] wrapper to build the entire project:
.. using Bash or Fish or PowerShell or Zsh: `./gradlew build`
.. using Windows Command Prompt: `.\gradlew build`

After a successful build,
artifacts will be found in "MinieLibrary/build/libs".

=== Quicker builds

In addition to the library, the Minie project includes subprojects for
assets and applications that take time to build.
To save time, you can build just the library subproject:

* using Bash or Fish or PowerShell or Zsh: `./gradlew :MinieLibrary:build`
* using Windows Command Prompt: `.\gradlew :MinieLibrary:build`

To save even more time, you can skip the automated tests:

* using Bash or Fish or PowerShell or Zsh: `./gradlew :MinieLibrary:assemble`
* using Windows Command Prompt: `.\gradlew :MinieLibrary:assemble`

=== Local installation

You can install the built artifacts to your local Maven repository:

* using Bash or Fish or PowerShell or Zsh: `./gradlew install`
* using Windows Command Prompt: `.\gradlew install`


== Customizing native libraries

The standard build is very convenient.
However, it's sub-optimal for many situations.

=== Debug builds

During application development, debug-enabled native libraries should be used.
Most Minie releases provide a "+debug" build of the library for this purpose.
You can replicate it by adding the "-Pbtdebug" option to the build command:

* using Bash or Fish or PowerShell or Zsh: `./gradlew -Pbtdebug clean build`
* using Windows Command Prompt: `.\gradlew -Pbtdebug clean build`

NOTE: Don't confuse the "-Pbtdebug" option with "-Pdebug",
which had special significance to certain old versions of Gradle.

=== Double-precision builds

Some applications may benefit from double-precision native libraries.
Most Minie releases provide "+dp" and "+debugdp" builds of the library,
which you can replicate by adding the "-Pdp" option to the build command.

=== Multithreaded builds

Some applications may benefit from multithreaded native libraries.
Some Minie releases provide "+mt" builds of the library,
which you can replicate by specifying the "-Pmt" option in the build command.

=== Reduced builds

Supporting 10 platforms requires 10 native libraries,
which results in a big, fat JAR and (potentially) a bloated application.
To address bloat, most Minie releases provide reduced builds that
don't support all 10 platforms.
These include:

* a "+big4" build (built with the "-Pbig4" option)
  with support for just the 4 major desktop platforms
  (Linux64, MacOSX64, MacOSX_ARM64, and Windows64)
* a "+bare" build (built with the "-Pbare" option)
  which doesn't include *any* native libraries
  (so you can add exactly the ones you want)
* a "+droid" build (built with the "-Pdroid" option)
  with support for just the 4 Android platforms

[NOTE]
====
Native libraries aren't published for every possible combination of options.
For instance, if you want Dp native libraries for Android platforms,
you'll probably have to build them yourself.
For more information,
see https://github.com/stephengold/Libbulletjme[the Libbulletjme project].
====


== Website

. Download and extract the source code from GitHub:
.. `git clone https://github.com/stephengold/Minie.git`
.. `cd Minie`
. Edit "src/site/antora/playbook.yml" and replace "/home/sgold/NetBeansProjects/Minie"
  with an absolute path to your checkout directory (3 places).
. https://docs.antora.org/antora/latest/install-and-run-quickstart/#install-nodejs[Install Node.js]
. Install Antora: `npm i -D -E @antora/cli@3.1`
. Run Antora: `npx antora src/site/antora/playbook.yml`

After a successful build,
your local copy of the site will be found in "build/site".


== Cleanup

At any time, you can restore the project to a pristine state:

* using Bash or Fish or PowerShell or Zsh: `./gradlew clean`
* using Windows Command Prompt: `.\gradlew clean`
