= An overview of the demo applications
:Project: Minie
:experimental:
:url-code: https://github.com/stephengold/Minie/tree/master/MinieExamples/src/main/java/jme3utilities/minie/test

_Demo applications_ are provided to showcase certain features of {Project}.
The following demos are found in
{url-code}[the "jme3utilities.minie.test" package of the MinieExamples sub-project]:

* `BalanceDemo`
  demonstrates ragdolls that balance their weight between 2 feet
* `BuoyDemo`
  demonstrates ragdolls with buoyancy
* `ConveyorDemo`
  demonstrates conveyor belt simulation using the `ContactListener` interface
* `DropTest` (also known as `MultiSphereDemo`)
  demonstrates falling rigid bodies with various shapes
* `ForceDemo`
  demonstrates forces, torques, and impulses applied in zero gravity
* `JointDemo`
  demonstrates a crawling robot composed of boxes and 6-DOF joints
* `NewtonsCradle`
  demonstrates dynamic restitution and point-to-point joints
* `PoolDemo`
  demonstrates 3 kinds of dynamic friction
* `RopeDemo`
  demonstrates simulation of ropes using `DynamicAnimControl`
* `SeJointDemo`
  demonstrates various kinds of single-ended physics joints
* `TargetDemo`
  demonstrates shooting balls at various targets
* `TestDac`
  demonstrates `DynamicAnimControl` applied to various models
* `TestGearJoint`
  demonstrates `GearJoint`
* `TestSoftBody`
  demonstrates soft-body physics without `SoftBodyControl`
* `TestSoftBodyControl`
  demonstrates soft-body physics using `SoftBodyControl`
* `TrackDemo`
  demonstrates inverse kinematics using `IKController`
* `WatchDemo`
  demonstrates head/eye inverse kinematics for various models

(Not all applications in the package are intended as demos;
those not listed above are primarily for testing purposes.)

For some of the demos, video walkthrus are available from YouTube.

The demos are controlled by primarily by keyboard input.
Each includes a _help node_
that displays a brief description of each key's function.

NOTE: The descriptions below assume a keyboard with the "US" (QWERTY) layout.
On keyboards with other layouts, the keys may be labeled differently:
refer to the help nodes for localized key labels.

For convenience, the mapping of keys to actions
is largely standardized.
In most demos:

* kbd:[H] toggles the help node between minimized and full-sized versions,
* kbd:[F5] toggles visibility of the render-statistics overlay,
* kbd:[O] dumps the physics space to the console,
* kbd:[C] dumps the camera's position to the console, and
* kbd:[Esc] ends the application.

For camera control, all demos use
the standard `FlyByCamera` with `setDragToRotate(true)`.
This means you can rotate the camera
by dragging with the left mouse button (LMB).
Furthermore:

* kbd:[W] and kbd:[S] dolly the camera forward and back, respectively,
* kbd:[A] and kbd:[D] dolly the camera left and right, respectively,
* kbd:[Q] and kbd:[&uarr;] raise the camera, and
* kbd:[Z] and kbd:[&darr;] lower the camera.

Some of the demos (such as `DropTest` and `TargetDemo`)
rely entirely on debug visualization to render the physics objects.
Others (such as `TestDac` and `PoolDemo`) use physics controls.
When physics controls are in use,
kbd:[/] toggles debug visualization on and off.
