= An overview of the demo applications
:Project: Minie
:experimental:
:url-examples: https://github.com/stephengold/Minie/tree/master/MinieExamples/src/main/java/jme3utilities/minie/test

_Demo applications_ are provided to showcase certain features of {Project}.
The following demos are found in
{url-examples}[the "jme3utilities.minie.test" package of the MinieExamples sub-project]:

* {url-examples}/BalanceDemo.java[`BalanceDemo`]
  demonstrates ragdolls that balance their weight between 2 feet
* {url-examples}/BuoyDemo.java[`BuoyDemo`]
  demonstrates ragdolls with buoyancy
* {url-examples}/ConveyorDemo.java[`ConveyorDemo`]
  demonstrates contact-point modifications
* {url-examples}/DropTest.java[`DropTest`] (also known as `MultiSphereDemo`)
  demonstrates falling rigid bodies with various shapes
* {url-examples}/ForceDemo.java[`ForceDemo`]
  demonstrates forces, torques, and impulses applied in zero gravity
* {url-examples}/JointDemo.java[`JointDemo`]
  demonstrates a crawling robot composed of boxes and 6-DOF joints
* {url-examples}/NewtonsCradle.java[`NewtonsCradle`]
  demonstrates dynamic restitution and point-to-point joints
* {url-examples}/Pachinko.java[`Pachinko`]
  demonstrates compound collision shapes and 2-D physics
* {url-examples}/PoolDemo.java[`PoolDemo`]
  demonstrates 3 kinds of dynamic friction
* {url-examples}/RopeDemo.java[`RopeDemo`]
  demonstrates simulation of ropes using `DynamicAnimControl`
* {url-examples}/SeJointDemo.java[`SeJointDemo`]
  demonstrates various kinds of single-ended physics joints
* {url-examples}/SplitDemo.java[`SplitDemo`]
  demonstrates dynamic splitting of rigid bodies
* {url-examples}/SweepDemo.java[`SweepDemo`]
  demonstrates the use of `sweepTest()` to detect of sword hits
* {url-examples}/TargetDemo.java[`TargetDemo`]
  demonstrates shooting balls at various targets
* {url-examples}/TestDac.java[`TestDac`]
  demonstrates `DynamicAnimControl` applied to various models
* {url-examples}/TestGearJoint.java[`TestGearJoint`]
  demonstrates a gear joint
* {url-examples}/TestSoftBody.java[`TestSoftBody`]
  demonstrates soft-body physics without `SoftBodyControl`
* {url-examples}/TestSoftBodyControl.java[`TestSoftBodyControl`]
  demonstrates soft-body physics using `SoftBodyControl`
* {url-examples}/TrackDemo.java[`TrackDemo`]
  demonstrates inverse kinematics using `IKController`
* {url-examples}/WatchDemo.java[`WatchDemo`]
  demonstrates head/eye inverse kinematics for various models
* {url-examples}/Windlass.java[`Windlass`]
  demonstrates rope simulation using rigid bodies

(Not all applications in the package are intended as demos;
those not listed above are primarily for testing purposes.)

For some of the demos, video walkthrus are available from YouTube.


== User interface

The demos are controlled primarily by keyboard input.
Each includes a _help node_
that displays a brief description of each key's function.

NOTE: The descriptions below assume a keyboard with the "US" (QWERTY) layout.
On keyboards with other layouts, the keys may be labeled differently:
refer to the help nodes for localized key labels.

For convenience, the mapping of keys to actions is partly standardized.
In most demos:

* kbd:[H] toggles the help node between minimized and full-sized versions,
* kbd:[F5] toggles visibility of the render-statistics overlay,
* kbd:[O] dumps the physics space to the console,
* kbd:[C] dumps the camera's position to the console, and
* kbd:[Esc] ends the application.

For camera control, all demos use
the standard `FlyByCamera` with `setDragToRotate(true)`.
This means you can rotate the camera
by dragging with the left mouse button (LMB).
Furthermore:

* kbd:[W] and kbd:[S] dolly the camera forward and back, respectively,
* kbd:[A] and kbd:[D] dolly the camera left and right, respectively,
* kbd:[Q] and kbd:[&uarr;] raise the camera, and
* kbd:[Z] and kbd:[&darr;] lower the camera.

Some of the demos (such as `DropTest` and `TargetDemo`)
rely entirely on debug visualization to render the physics objects.
Others (such as `TestDac` and `PoolDemo`) use physics controls.
When physics controls are in use,
kbd:[/] toggles debug visualization on and off.
