= Library version dependencies

Each release of the Minie library targets specific versions
of the libraries it depends on, such as "jme3-core", "Heart", and "sim-math".
The targeted versions are usually
the most-recent production/stable versions at the time of release.
Since libraries strive to maintain backward compatibility,
versions other than the targeted ones will often work just fine.
However, it's slightly safer
to stick to library combinations that were built (and tested) together.

In case you want to use Minie
without upgrading one or more of the libraries it depends on,
the following table may help you decide which release to use.

[cols="1,4,2",grid="none"]
|===
|Minie release |direct dependencies |indirect dependencies

|v4.8.0
|Heart v7.4.1, sim-math v1.4.1, jme3-terrain v3.5.1-stable
|jme3-core v3.5.1-stable

|v4.7.1
|Heart v7.4.1, sim-math v1.4.1, jme3-terrain v3.5.0-stable
|jme3-core v3.5.0-stable

|v4.6.1
|Heart v7.2.0, sim-math v1.4.1, jme3-terrain v3.5.0-stable
|jme3-core v3.5.0-stable

|v4.6.0
|Heart v7.1.0, sim-math v1.4.1, jme3-terrain v3.4.1-stable
|jme3-core v3.4.1-stable

|v4.5.0
|Heart v7.1.0, sim-math v1.4.1, jme3-terrain v3.4.0-stable
|jme3-core v3.4.0-stable

|v4.4.0
|Heart v7.1.0, sim-math v1.4.1, jme3-terrain v3.4.0-stable
|jme3-core v3.4.0-stable

|v4.3.0
|Heart v7.0.0, jme3-terrain v3.4.0-stable
|jme3-core v3.4.0-stable

|v4.2.0
|Heart v6.4.4, jme3-terrain v3.4.0-stable
|jme3-core v3.4.0-stable

|v4.1.1
|Heart v6.4.4, jme3-terrain v3.4.0-stable
|jme3-core v3.4.0-stable

|v4.1.0+for33
|Heart v6.4.3+for33, jme3-terrain v3.3.2-stable
|jme3-core v3.3.2-stable

|v4.0.2
|Heart v6.4.2, jme3-terrain v3.3.2-stable
|jme3-core v3.3.2-stable

|v4.0.2
|Heart v6.4.2, jme3-terrain v3.3.2-stable
|jme3-core v3.3.2-stable

|v4.0.1
|Heart v6.4.2, jme3-terrain v3.3.2-stable
|jme3-core v3.3.2-stable

|v4.0.0
|Heart v6.4.2, jme3-terrain v3.3.2-stable
|jme3-core v3.3.2-stable

|v1.6.0+for32
|Heart v5.2.0for32, jme3-terrain v3.2.4-stable
|jme3-core v3.2.4-stable

|===

Additional details about each release
(such as bugfixes, features, and release dates) can be found in the
https://github.com/stephengold/Minie/blob/master/MinieLibrary/release-notes.md[release log].

NOTE: All releases mentioned the table above
are available from the Maven Central Repository.
However, Minie's release log describes many releases
that haven't been published to Maven Central.
