= How Minie works
:Cplusplus: C&#43;&#43;
:Project: Minie
:url-enwiki: https://en.wikipedia.org/wiki

For physics simulation and collision detection,
{Project} uses https://pybullet.org/wordpress[the _Bullet Physics SDK_],
a mature, open-source, 3-D physics simulator,
released under https://github.com/bulletphysics/bullet3/blob/master/LICENSE.txt[a Zlib license].

To enable efficient simulation of moving meshes,
{Project} also incorporates Khaled Mamou's
https://github.com/kmammou/v-hacd[Volumetric-Hierarchical Approximate Convex Decomposition _(V-HACD)_ algorithm].

== Native libraries

Bullet and V-HACD are written in {Cplusplus}, so {Project} uses
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/intro.html[the Java Native Interface (JNI)]
to access their objects and methods.

All {Cplusplus} source code associated with {Project}
(including a modified partial snapshot of Bullet, a snapshot of V-HACD, and some "glue code")
resides in https://github.com/stephengold/Libbulletjme[the Libbulletjme repository].
Before instantiating physics objects,
a {Project} application must {url-enwiki}/Dynamic_loading[dynamically load]
a _native library_ of this code,
compiled for the {url-enwiki}/Computing_platform[platform]
on which the app is executing.

The Libbulletjme project publishes native libraries
for the 13 platforms {Project} supports:

* Windows (32-bit and 64-bit),
* Linux (x86-64, x86, armhf, and aarch64),
* macOS (x86-64, IA-32, and ARM64), and
* Android (armeabi-v7a, arm64-v8a, x86, and x86_64).

NOTE: 32-bit and 64-bit versions of the same operating system
count as distinct platforms!

On desktop platforms, JMonkeyEngine automatically loads
the appropriate native library
during initialization of the `JmeDesktopSystem` class
if it detects Minie's `NativeMeshUtil` class.
On Android platforms, the native library is loaded (if present)
during static initialization of the `JmeAndroidSystem` class.

== Collision objects, spaces, and shapes

Collision detection is organized around _collision objects_
that interact in the context of a _collision space_.
Collision objects can be _soft_ (varying shape) or _rigid_ (non-varying shape).
Rigid objects can be _mobile_ (moving) or _static_ (non-moving).
And mobile objects can be _dynamic_ (driven by {url-enwiki}/Force[forces],
{url-enwiki}/Torque[torques], and {url-enwiki}/Impulse_(physics)[impulses])
or _kinematic_ (driven directly by external calculations).

In {Project}, collision spaces that simulate forces, torques, and impulses
are referred to as _physics spaces_.

By themselves, collision objects are invisible,
while scene-graph spatials have no effect on physics.
To visualize a collision object, it must be associated
with one or more scene-graph spatial(s).
For debugging purposes, Minie can visualize
collision objects by auto-generating spatials for them.
For full-custom visualization, a _physics control_
should be used to associate collision objects with spatials.

Each rigid collision object references a _collision shape_
that describes the shape of its surface.
Most collision shapes are _scalable_,
allowing you to grow or shrink objects
simply by varying the shape's scale factors.

== Coordinate systems and units

A collision object's absolute location and orientation are quantified
in _physics-space coordinates_,
based on a right-handed Cartesian coordinate system.
These typically correspond to world coordinates of the scene.
However, Minie supports scaling the physics space relative to the scene,
in which case the _physics-space units_ (psu)
might differ the from world units (wu).

With notable exceptions,
{Project} doesn't specify real-world units for distance.
Instead, its documentation refers to physics-space units,
which could be light-years or millimeters, depending on the application.
Nor does {Project} specify which axis serves as the "up" direction.
If you use a Y-up coordinate system with a psu of one meter,
then {Project}'s default gravity
will be roughly correct for the Earth's surface.
However, there are good reasons to use physics-space units other than meters.

Locations relative to a collision object's center and subject to its rotation
are quantified using _local coordinates_.
The documentation distinguishes _scaled local coordinates_ (measured in psu)
from _shape coordinates_ (which depend on scale factors).

== Discrete time and collision detection

Within a physics space, simulation occurs in discrete steps.
While it's possible to vary the time step from step to step,
a fixed time step tends to yield more reproducible results.

Each time step consists of 4 _phases_:

. _forward dynamics part one_,
  to apply known forces and torques
  and predict the next position of each collision object,
. _broadphase collision detection_,
  to quickly determine (using axis-aligned bounding boxes)
  which object pairs might possibly collide,
. _narrowphase collision detection_,
  to compute actual contacts (if any) between between objects, and
. _forward dynamics part 2_,
  to apply contact forces, solve constraints, and update positions.

Collisions are reported to listeners registered at the space.
For fast-moving objects,
{Project} offers optional continuous collision detection (CCD)
using swept spheres.
Collisions detected by CCD are reported to those same listeners.

== App states

To simplify the creation and management of physics spaces,
Minie provides _app states_.
The simplest of these is `BulletAppState`; it manages a single
space without any soft objects or multibodies.
Simulation of the space can take place on the render thread
or else on a dedicated _physics thread_.
Either way, the app state attempts to synchronize to real time
during each rendered frame.

Debug visualization can be enabled or disabled simply by setting a parameter.

== Direct buffers, garbage collection, and threading

Direct buffers used in {Project} should have native byte order.

All other native objects created by {Project} are carefully tracked using
weak references.

Successful initialization of a native library causes {Project}
to start a daemon thread named "Physics Cleaner".
Its purpose is to free any tracked native objects
whose corresponding java objects have been garbage collected.

As a performance enhancement,
{Project} can parallelize certain for-loops on platforms that support OpenMP.
To enable this feature, a multi-threaded native library must be loaded.


== Next steps

For more detail about Bullet physics, download and read the
https://github.com/bulletphysics/bullet3/blob/master/docs/Bullet_User_Manual.pdf[Bullet User Manual].

To gain hands-on experience,
proceed to xref:minie-library-tutorials:add.adoc[the first tutorial page].
