= Project overview
:url-enwiki: https://en.wikipedia.org/wiki

_Minie_ is a physics library for https://jmonkeyengine.org[JMonkeyEngine]
that takes physics-based games to the next level.

Use it to:

* add solidity to walls, characters, projectiles, landscapes, and vehicles,
* detect collisions between complex shapes,
* perform contact, ray, and sweep tests,
* simulate characters and buildings collapsing in real time, and
* simulate cloth, rope, and deformable volumes,
  including their interactions with rigid bodies and each other.

Forked from the jme3-bullet library, Minie adds many useful features
while preserving most of the jme3-bullet
{url-enwiki}/Application_programming_interface[API].
Most JMonkeyEngine physics examples can use Minie without modification,
and Minie adds its own demos and tutorials to help you get started.

All software in the Minie project is free and open-source,
including the library itself, the demo, tutorial, and utility apps,
and the software used to build, test, and run them.

The underlying simulation software  comes from
https://pybullet.org/wordpress[_Bullet_], a mature real-time physics simulator.
But although Bullet is written in {url-enwiki}/C%2B%2B[C&#43;&#43;],
you won't need any knowledge of C&#43;&#43; to use Minie.

== Caveats

Minie's focus is on simulating
{url-enwiki}/Classical_mechanics[classical mechanics]
in just enough detail to add verisimilitude to 3-D games.
It's not intended for 2-D {url-enwiki}/Platform_game[platformers],
nor for scientific research.
For 2-D physics, consider using http://www.dyn4j.org/[dyn4j] instead.

Starting with version 1.6,
Minie no longer supports the version 3.2.x JMonkeyEngine libraries.
In order to use the latest Minie release,
you'll need version 3.3.x JMonkeyEngine libraries, preferably v3.3.2-stable.
(You can still use the JME 3.2 SDK, however.)

Like JMonkeyEngine, Minie and its documentation
assume a certain level of proficiency with
{url-enwiki}/Java_(programming_language)[the Java programming language].
This project isn't aimed at non-programmers,
nor developers without prior Java experience.
Similarly, some familiarity with 3-D graphics and vector math is assumed.

While an understanding of classical mechanics is assumed,
many of its technical terms are linked (at first use)
to the relevant article in the English Wikipedia.

https://raw.githubusercontent.com/stephengold/Minie/master/LICENSE[Minie's BSD-style license]
disclaims liability for defects.
Please don't use this software in safety-critical applications.

== The name

The Minie project is named after
{url-enwiki}/Claude-%C3%89tienne_Mini%C3%A9[_Claude-Étienne Minié_],
who in 1846 developed an improved bullet for rifles.
It's a play on words, not intended to denigrate the man, nor glorify him.

The preferred English pronunciation is roughly "min-YAY",
but "MIN-ee" is also acceptable.

== Next steps

If you're curious how Minie works,
proceed to xref:implementation.adoc[the Implementation page].

To gain hands-on experience,
proceed to xref:minie-library-tutorials:add.adoc[the first tutorial page].