= Miscelaneous tutorial material
:experimental:
:url-enwiki: https://en.wikipedia.org/wiki
:url-examples: https://github.com/stephengold/Minie/blob/master/MinieExamples/src/main/java/jme3utilities/minie/test
:url-tutorial: https://github.com/stephengold/Minie/blob/master/MinieExamples/src/main/java/jme3utilities/tutorial

This page acts as a holding area for tutorial material that's waiting
to be organized.

== Global configuration

By default, the native library prints a startup message to `System.out`.
Once the library is loaded (but not started) you can disable this message:

[source,java]
----
NativeLibrary.setStartupMessageEnabled(false);
----

Once the native library is loaded,
you can test whether it uses double-precision arithmetic:

[source,java]
----
boolean doublePrecision = NativeLibrary.isDoublePrecision();
----

You can also test whether it was built for debugging
(with assertions enabled, symbols not stripped,
and debug information generated):

[source,java]
----
boolean debug = NativeLibrary.isDebug();
----

The default collision margin for new shapes is 0.04 physics-space units.
To configure a default margin of 0.1 psu:

[source,java]
----
CollisionShape.setDefaultMargin(0.1f);
----

NOTE: The Bullet Manual advises against changing the default margin.

== Advanced rigid-body friction

Because friction can generate both forces and torques,
modeling it can get very complicated.

In addition to its basic friction parameter,
each rigid body has 2 additional friction parameters:
one for rolling friction and one for spinning friction.
Both parameters default to zero.

_Rolling friction_ creates torque orthogonal to the contact normal,
which tends to slow down a rolling body.
_Spinning friction_ creates torque parallel to the contact normal,
which tends to prevent a body from spinning when grasped.

To see rolling and spinning friction in action, run
{url-examples}/PoolDemo.java[the PoolDemo application].

To simulate objects with grooved surfaces, it's also possible to configure
a rigid body for _anisotropic friction_:
friction that depends on the direction of relative motion.