= Physics simulation without appstates
:url-api: https://stephengold.github.io/Minie/minie/javadoc/com/jme3/bullet
:url-tutorial: https://github.com/stephengold/Minie/blob/master/MinieExamples/src/main/java/jme3utilities/tutorial

The {url-api}/BulletAppState.html[`BulletAppState`] class
provides a convenient interface
for configuring, accessing, updating, and debugging
a {url-api}/PhysicsSpace.html[`PhysicsSpace`].

However, if an application doesn't require debug visualization,
it can instantiate a space directly and update it explicitly.

{url-tutorial}/HelloUpdate.java[HelloUpdate] is a simple
application that demonstrates direct instantiation and explicit updating.

Furthermore, an application running in a headless environment
(such as a server) might not even need a scene graph.
By instantiating collision objects directly (not using physics controls),
you can simulate physics without a scene graph.

And by using `NativeLibraryLoader` to explicitly load the native library,
such applications can completely avoid initializing JMonkeyEngine.

{url-tutorial}/HelloConsole.java[HelloConsole] is a console
application that demonstrates explicitly loading the native library.

For applications without a scene graph, consider using
https://github.com/stephengold/Libbulletjme[Libbulletjme] instead of Minie.

== Constructing the space

There are 7 ways to explicitly construct a
{url-api}/PhysicsSpace.html[`PhysicsSpace`]:

[source,java]
----
PhysicsSpace space1 = new PhysicsSpace(worldMin, worldMax, broadphase, solver);
PhysicsSpace space2 = new PhysicsSpace(worldMin, worldMax, broadphase);
PhysicsSpace space3 = new PhysicsSpace(worldMin, worldMax);
PhysicsSpace space4 = new PhysicsSpace(broadphase);
PhysicsSpace space5 = new PhysicsSoftSpace(worldMin, worldMax, broadphase);
PhysicsSpace space6
        = new MultiBodySpace(worldMin, worldMax, broadphase, solverType);
PhysicsSpace space7 = new MultiBodySpace(worldMin, worldMax, broadphase);
----

The first 4 methods can be used
*only* if soft bodies and multibodies will not be added to the space.

If the `solver` argument is omitted, then a
http://allenchou.net/2013/12/game-physics-constraints-sequential-impulse[Sequential Impulse (SI) solver]
will be used.

If the `broadphase` argument is omitted,
then the incremental 3-D sweep-and-prune
(`AXIS_SWEEP_3`) broadphase accelerator will be used.

If the `worldMin` and `worldMax` arguments are omitted, then the world
will extend from (-10000, -10000, -10000) to (+10000, +10000, +10000).

NOTE: World bounds are used *only* by
the sweep-and-prune broadphase accelerators
(`AXIS_SWEEP_3` and `AXIS_SWEEP_3_32`).
The `SIMPLE` and `DBVT` accelerators ignore them.

== Updating the space

{url-api}/PhysicsSpace.html[`PhysicsSpace`] offers 2 update methods:

[source,java]
----
space.update(timeInterval, maxSteps);
space.update(timeInterval);
----

To single-step the simulation, specify `maxSteps = 0`.
The time step will be `timeInterval` seconds.
Specifying the time step this way allows it to vary from step to step,
without regard for `space.getAccuracy()` or `space.maxTimeStep()`.

To attempt real-time simulation, specify `maxSteps` > 0.
The time step will be `space.getAccuracy()`
and up to `maxSteps` steps will be simulated for each update.

If the `maxSteps` argument is omitted, `space.maxSubSteps()` will be used.
And if `space.maxSubSteps() == 0`,
then the time step will be capped at `space.maxTimeStep()` seconds
(as with a {url-api}/BulletAppState.html[`BulletAppState`]).

== Summary

* It's possible to instantiate a space directly and update it explicitly.
* It's possible to load the native library explicitly
  and thus avoid initializing JMonkeyEngine.
* A scene graph is not required for physics simulation.