package vhacd.vhacd_native;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VHACDNativeResults extends Structure {
	public int n_hulls;
	public vhacd.vhacd_native.VHACDNativeConvexHull.ByReference hulls;
	public VHACDNativeResults() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("n_hulls", "hulls");
	}
	public VHACDNativeResults(int n_hulls, vhacd.vhacd_native.VHACDNativeConvexHull.ByReference hulls) {
		super();
		this.n_hulls = n_hulls;
		this.hulls = hulls;
	}
	public VHACDNativeResults(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VHACDNativeResults implements Structure.ByReference {
		
	};
	public static class ByValue extends VHACDNativeResults implements Structure.ByValue {
		
	};
}
