package vhacd.vhacd_native;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.ptr.FloatByReference;
import com.sun.jna.ptr.IntByReference;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>vhacd</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface VhacdLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "vhacd";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(VhacdLibrary.JNA_LIBRARY_NAME);
	public static final VhacdLibrary INSTANCE = (VhacdLibrary)Native.loadLibrary(VhacdLibrary.JNA_LIBRARY_NAME, VhacdLibrary.class);
	@Deprecated 
	VHACDNativeResults compute(FloatByReference points, int points_n, IntByReference triangles, int triangles_n, VHACDNativeParameters params, byte debug);
	VHACDNativeResults compute(FloatBuffer points, int points_n, IntBuffer triangles, int triangles_n, VHACDNativeParameters params, byte debug);
	void release(VHACDNativeResults results);
	void initParams(VHACDNativeParameters params);
}
